# Copyright 2020 Shivam Rathore
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build
on: [push, pull_request]
env:
  GO111MODULE: on

jobs:
  build:
    name: On ${{ matrix.os }} with Go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.15]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2.1.2
        with:
          go-version: ${{ matrix.go_version }}
        id: go
      - name: Check out code
        uses: actions/checkout@v2.3.3
      - name: Go mod verify
        run: go mod verify
      - name: Go vet normally
        run: go vet ./...
      - name: Go build
        run: go build ./...
